In [2]:
import numpy as np

In [2]:
a = [1, 3, 4]
print(a*2)

[1, 3, 4, 1, 3, 4]


In [14]:
a = np.arange(1, 6)
# a = np.arange(1,10,3)
a
print(a*2) #This process is called vectorization and numpy is a vectorized library.


[ 2  4  6  8 10]


In [13]:
a < 3 #This condition will be checked aginst each item in the list
#Similar to mapping.
#Also called broadcasting.

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False])

In [17]:
a

array([1, 2, 3, 4, 5])

In [19]:
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [21]:
a + b # Corresponding numbers gets added up
a * b #Corresponding numbers gets multiplied.

array([ 5, 12, 21, 32, 45])

In [22]:
#Matrix Multiplication
a.dot(a)

55

In [23]:
a.dot(b)

115

In [25]:
c = np.arange(12).reshape(1, 12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [32]:
d = np.arange(12).reshape(12,1)
# d.shape #Shape is a property not a method.
d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [31]:
d.T #Transpose of a matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [29]:
d.dot(c) #Matrix will get multiplied like usual matrix multiplication using dot function.

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121]])

In [9]:
#Reshaping the array
b = np.arange(1,5)
b.reshape(2,2)


array([[1, 2],
       [3, 4]])

In [10]:
#Creating a 2D-array
d = np.array([[1,2], [4,5]])
d 
#Creating a 3D-array
c = np.arange(24).reshape(2,3,4)
print(c[1,1,1])
print(c[0,2,3])
print(c[0,:,:])

17
11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
#Masking- Filtering
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
#Filtering
a[a>14]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
b = np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
b[b>14] 
#After filtering the returned matrix will no longer be of parent shape, it will change to vector form. In order to
#change the shape we will use reshape method.

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [51]:
#Reshaping
a = np.arange(12)
b = a.reshape(4, -1) #it will find its own with which to replace -1.Only one dimension can be -1
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.array([1,2,0.1, 3.2])

numpy.ndarray

In [55]:
#Creating some special arrays
np.zeros(5)
#In order to change the datatype of values from float to int, we can use dtype 
np.zeros(5, dtype='int8')

array([0, 0, 0, 0, 0], dtype=int8)

In [56]:
np.zeros((3,4)) #For 2D-matrix of zeros we need to give the tuple.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.ones(5)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
#We can also perform vectorization on the matrix as:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [61]:
np.empty((4,5)) #It will print out all the garbage values present in the jupyter notebook.

array([[1.38738839e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.06810200e-306],
       [5.30276956e+180, 1.57076922e-076, 4.57841355e-071,
        3.45696586e-086, 3.35758954e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 4.39490369e+175],
       [1.19925738e-071, 5.48804806e+170, 7.31680425e+169,
        4.66907366e-143, 1.50008929e+248]])

In [64]:
np.eye(5) #Returns an Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.linspace(1,5,5) #Third value is the partition value which divides the range in partitions
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [70]:
np.linspace(1, 100, 4)

array([  1.,  34.,  67., 100.])

In [23]:
#Declaring the array type
a = np.array([-1, 3, 0, 0.5, 199], dtype = "int8")
print(a*2)
b = a.astype("float32")
print(b*2)

[  -2    6    0    0 -114]
[  -2.    6.    0.    0. -114.]


In [34]:
#Indexing and Splicing
a = np.arange(12)
b = a[4:8]
b[0] = 99 #Changes done in this list will also be seen it parent list too.
print(a)
print(b)
print(a[2:7])
print(a[:8])
print(a[:])
print(a[::2])


[ 0  1  2  3 99  5  6  7  8  9 10 11]
[99  5  6  7]
[ 2  3 99  5  6]
[ 0  1  2  3 99  5  6  7]
[ 0  1  2  3 99  5  6  7  8  9 10 11]
[ 0  2 99  6  8 10]


In [71]:
#Analysis on Numpy array
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
a.sum()

66

In [73]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
b.sum()

66

In [75]:
b.sum(axis=0) #Going through row giving each column sum

array([12, 15, 18, 21])

In [76]:
b.sum(axis=1) #Going through columns giving each row sum

array([ 6, 22, 38])

In [78]:
c = np.arange(24).reshape(4,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [79]:
c.sum(axis=0) #Sum along depth

array([[36, 40],
       [44, 48],
       [52, 56]])

In [80]:
c.sum(axis=1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])

In [81]:
c.sum(axis=2)

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33],
       [37, 41, 45]])

In [83]:
#Statistical Analysis
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
b.max(axis =0)
b.max(axis=1)

array([ 3,  7, 11])

In [90]:
print(b.mean())
print(b.mean(axis=0))
print(b.mean(axis=1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [93]:
print(np.median(b)) #Median of b
print(np.median(b,axis=0))
print(np.median(b,axis=1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [94]:
#Standard deviation
np.std(b)

3.452052529534663

In [96]:
#Random Distributions
np.random.rand(4,5)

array([[0.84525254, 0.40006132, 0.1445321 , 0.43593005, 0.28227879],
       [0.22509995, 0.27605778, 0.62750927, 0.40990969, 0.25788723],
       [0.60877267, 0.04553159, 0.74589163, 0.72199347, 0.79386533],
       [0.82978308, 0.25510401, 0.93950528, 0.77346089, 0.32033544]])

In [97]:
90 + np.random.rand(4,5)*10

array([[92.11540357, 96.31795166, 96.69080161, 90.92556644, 93.05137563],
       [96.61866221, 93.62319929, 95.81962376, 93.26888516, 94.91832433],
       [91.89798507, 95.58357157, 95.81579002, 99.02576884, 98.54945901],
       [99.535096  , 93.02551967, 98.02891802, 96.74709116, 93.42491747]])

In [102]:
np.random.randint(40,80,5)

array([40, 60, 49, 68, 74])

In [106]:
np.random.seed(32)
np.random.rand()

0.8588892672930397

In [109]:
#Normal Distribution
mu = 100
sigma = 15
s = np.random.normal(mu, sigma, 100)
print(s)

[105.31919068  96.29997084  90.04032418  96.33599112 114.71219735
 103.67904983  83.28387225  83.46051675  98.26035062 117.81253929
  89.97026958 103.12854295  81.83099256  67.25005066 114.18833982
  76.45429782 100.52974906 114.87558374  91.86190981  92.07227306
  67.3064084  135.14960144 115.84269394 101.05330218  99.92468211
 101.81175541  94.61207586 113.07667145  87.67157964 109.36321528
  72.82824316 101.64158969 101.13692447  80.94068374  84.10519609
  68.38211078 130.32118217 112.92270575 121.55007088 107.05506748
 122.60332574 106.02350845  85.5565832  105.9844429   90.6432401
 111.51249351 100.50849629  86.00377197  89.01691462  95.35574181
 108.22863245 102.76565627  73.11710623 113.87523028  86.41984169
  91.00346513  93.36456528  81.1165527   90.06160321  82.46927159
 132.51414102  74.08715272  95.18409509  94.523765    79.8852768
  88.08685619  79.53560758 107.89979758 104.10156411  77.60961916
 126.22430516  99.13780516  77.81388608 110.0383997  112.1184641
 126.88292277

In [110]:
np.mean(s)

97.17625413886158

In [111]:
np.std(s)

14.838793817567

In [114]:
#Sorting in Numpy
d = np.random.randint(1,9,(3,4))
d

array([[1, 7, 8, 3],
       [1, 5, 1, 2],
       [7, 7, 6, 2]])

In [116]:
d.sort()
d

array([[1, 3, 7, 8],
       [1, 1, 2, 5],
       [2, 6, 7, 7]])

In [119]:
d=d.flatten()


In [121]:
d.sort()
d

array([1, 1, 1, 2, 2, 3, 5, 6, 7, 7, 7, 8])

In [122]:
d = d.reshape(3,4)

array([[1, 1, 1, 2],
       [2, 3, 5, 6],
       [7, 7, 7, 8]])